name: test
on: ['push']
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: perl version
        run: perl -v
      - name: install deps
        run: cpanm -n --installdeps .
      - name: test
        run: prove -lv
